### PR TITLE
Merge pull request #1 from lawsonkeith/master

### PR DESCRIPTION
**Pull request by MascotFlyer**
https://github.com/MascotFlyer/PiCar-Revisited-with-ZeroRPC

### CODE REVIEW

**Comment by MascotFlyer** [comment]
Not sure how to contact you.  tony.bloomfield@blueyonder.co.uk

**Comment by lawsonkeith** [comment]
Yeah nice project.  Have a look at my Protobot project as well that's teleoperated and uses an XBOX controller.  Fairly sure the hardware's the same you just run it off a Linux VM.  I'll probably not merge though since your project looks a bit different.  Good luck with it all I've used a lot of the stuff I learnt doing this lot to good effect at work, definitely worth doing.

**Comment by MascotFlyer** [comment]
Praise indeed! Thanks Keith.

 

Two questions since I am feeling my way with GitHub.

 

How did you come to get my email? I am not sure what I did.

How do you get a normal looking README.md with pictures and tables?

 

Regards

Tony

**Comment by lawsonkeith** [comment]
Hi

Yeah if you do a pull you're asking me to incorporate all your changes into
my master rep you cloned.  Just do commits.

For the pics you need them in your repository then you just put the file
reference in your markdown text.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet


Best regards

Keith

**Pull request closed without merging**
